export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_WHOLE_ITEM = 'REMOVE_WHOLE_ITEM'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const INIT = 'INIT'
export const CLEAR_ALL_CART = 'CLEAR_ALL_CART'
